#! /bin/sh

#
# Customizations for BSPWM : https://github.com/baskerville/bspwm
# Original available @ https://github.com/EndeavourOS-Community-Editions/bspwm/blob/main/.config/bspwm/bspwmrc
# Usually located in .config/bspwm/bspwmrc
#

#
# BPSC Config Section
#

# Merge both the laptop + external monitors.
# bspc config merge_overlapping_monitors true

# Number of work-spaces
bspc monitor -d I II III IV

bspc config window_gap          13
bspc config split_ratio          0.69
bspc config gapless_monocle      true
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true

# Border
bspc config border_width         3
bspc config borderless_monocle   true
bspc config focused_border_color        "#6c71c4"
bspc config normal_border_color         "#073642"
bspc config active_border_color         "#073642"

bspc rule -a google-chrome desktop='^2'

#
# Autostart / Autosetup other tools.
#

# Disable screen blanking.
xset s off
xset s noblank
xset -dpms
xset dpms 0 0 0

# Set brigtness to max value on both nonitors.
xrandr --output HDMI1 --brightness 1.0 --output eDP1 --brightness 1.0

# restart sxhkd if already running.
pgrep -x sxhkd > /dev/null || sxhkd &

# Set a scaled random wallpaper
feh --bg-scale --randomize ~/Pictures/wpapers/main_desktop/*

# Launch Bar
~/.config/polybar/launch.sh &

# Notifications
/usr/bin/dunst &

# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Dex - DesktopEntry Execution
dex -a -s /etc/xdg/autostart/:~/.config/autostart/  

# Picom
# picom -CGb &

# Network Applet
nm-applet --indicator &

# Cursor
xsetroot -cursor_name left_ptr &

# Low battery notifier
~/.config/bspwm/scripts/low_bat_notifier.sh
