#! /bin/sh

#
# Customizations for BSPWM : https://github.com/baskerville/bspwm
# Usually located in ~/.config/bspwm/bspwmrc on the local system
# Original available @ https://github.com/EndeavourOS-Community-Editions/bspwm/blob/main/.config/bspwm/bspwmrc
#

# Load Configuration variable file
. ~/.dotConfigs/scripts/set-variables.sh

#
# BPSWM related configuration setup
#

# Monitors
bspc monitor -d & R U
#bspc config merge_overlapping_monitors true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc config split_ratio $BSPWM_SPLIT_RATIO
bspc config single_monocle true
bspc config ignore_ewmh_focus true

# Gaps and Padding
bspc config window_gap $BSPWM_GAP
for side in top right bottom left ; do
	bspc config ${side}_padding $BSPWM_PAD
done
bspc config gapless_monocle true
bspc config gapless_monocle true

# Focus
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true

# Border
bspc config border_width $BSPWM_BORDER
bspc config borderless_monocle   true

# Window / Workspace rules
bspc rule -a google-chrome desktop='^2'
bspc rule -a Onboard state=floating sticky=on

#
# Auto-(Start / Setup) other tools.
#

# Disable screen blanking.
xset s off
xset s noblank
xset -dpms
xset dpms 0 0 0

# Set brightness to max value on both monitors.
xrandr --output HDMI1 --brightness 1.0 --output eDP1 --brightness 1.0

# restart sxhkd if already running.
pgrep -x sxhkd > /dev/null || sxhkd &

# Set a scaled random wallpaper
feh --no-fehbg --bg-scale --randomize ~/Pictures/wpapers/main_desktop/*

# Launch Bar
~/.config/polybar/launch.sh &

# Notifications
/usr/bin/dunst &

# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Dex - Desktop Entry Execution
dex -a -s /etc/xdg/autostart/:~/.config/autostart/

# Picom
# picom -CGb &

# Network Applet
nm-applet --indicator &

# Cursor
xsetroot -cursor_name left_ptr &

# Low battery notifier
~/.config/bspwm/scripts/low_bat_notifier.sh

#
# Notify that restart is completed
#
dunstify "Restarted BSPWM"

