#! /bin/sh

#
# Customizations for BSPWM : https://github.com/baskerville/bspwm
# Usually located in ~/.config/bspwm/bspwmrc on the local system
# Original available @ https://github.com/EndeavourOS-Community-Editions/bspwm/blob/main/.config/bspwm/bspwmrc
#

# Merge both the laptop + external monitors.
#bspc config merge_overlapping_monitors true

# Number of work-spaces
bspc monitor -d A N D

BW=3
GAP=1
PAD=10
bspc config border_width $BW
bspc config window_gap $GAP
for side in top right bottom left ; do
	bspc config ${side}_padding $PAD
done

bspc config split_ratio          0.53
bspc config gapless_monocle      true
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true

# Border
bspc config border_width         3
bspc config borderless_monocle   true

# Window / Workspace rules
bspc rule -a google-chrome desktop='^2'
bspc rule -a Onboard state=floating sticky=on

#
# Auto-(Start / Setup) other tools.
#

# Disable screen blanking.
xset s off
xset s noblank
xset -dpms
xset dpms 0 0 0

# Set brightness to max value on both monitors.
xrandr --output HDMI1 --brightness 1.0 --output eDP1 --brightness 1.0

# restart sxhkd if already running.
pgrep -x sxhkd > /dev/null || sxhkd &

# Set a scaled random wallpaper
feh --no-fehbg --bg-scale --randomize ~/Pictures/wpapers/main_desktop/*

# Launch Bar
~/.config/polybar/launch.sh &

# Notifications
/usr/bin/dunst &

# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Dex - Desktop Entry Execution
dex -a -s /etc/xdg/autostart/:~/.config/autostart/

# Picom
# picom -CGb &

# Network Applet
nm-applet --indicator &

# Cursor
xsetroot -cursor_name left_ptr &

# Low battery notifier
~/.config/bspwm/scripts/low_bat_notifier.sh

